const Verifier = artifacts.require('Verifier');
const proof_one = require('./proof_1.json'); //with path
const proof_two = require('./proof_2.json'); //with path



// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

// Test verification with correct proof
// - use the contents from proof_1.json generated from zokrates steps


// Test verification with incorrect proof


contract('Test ZoKrates Verifier', accounts => {
    let contract;

    beforeEach(async function () {
        contract = await Verifier.new();
    });

    describe('Verify Square', function () {
        it('verifies correct proof', async function () {
            let result = await contract.verifyTx.call(
                proof_one.proof.a,
                proof_one.proof.b,
                proof_one.proof.c,
                proof_one.inputs);
            assert.isTrue(result);
        });
        it('rejects incorrect proof', async function () {
            let result = await contract.verifyTx.call(
                proof_one.proof.a,
                proof_one.proof.b,
                proof_one.proof.c,
                proof_two.inputs);
            assert.isFalse(result);
        });

    });
});
