const Verifier = artifacts.require('Verifier');

// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps


// Test verification with incorrect proof


contract('Test ZoKrates Verifier', accounts => {

    beforeEach(async function () {
        contract = await Verifier.new();
    });

    describe('Check Verifier', function () {
        it('do something');
    });
});
